DROP DATABASE IF EXISTS db;

CREATE DATABASE db;

USE db;

CREATE TABLE tableName (
    id INT AUTO_INCREMENT NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY(id)
);
